#see options here: https://github.com/realm/SwiftLint

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - pods

disabled_rules:
 - superfluous_disable_command

line_length:
  warning: 300
  error: 400
  ignores_comments: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
