os: osx
language: swift
osx_image: xcode11.4

branches:
  only: 
    - master

git:
  depth: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
- brew install git-lfs

before_script:
- git lfs pull

script:
  - echo "Check if the library described by the podspec can be built"
    - pod lib lint
  - echo "Build as static library"
    - xcodebuild clean build -project Name/Name.xcworkspace -scheme 'Name' -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone X” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -configuration Release | xcpretty -c
  - echo "Build test app"
    - xcodebuild clean build -project Name/Name.xcworkspace -scheme 'NameSample' -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone X” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -configuration Release | xcpretty -c
