os: osx
language: swift
osx_image: xcode11.4

branches:
  only: 
    - master

git:
  depth: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
- brew install git-lfs

before_script:
- git lfs pull

# Workspace
script: xcodebuild clean build -workspace SoloRocket/SpaceShip.xcworkspace -scheme 'SpaceShip' -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone X” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

# Project
script: xcodebuild clean build test -project SampleName/SampleName.xcodeproj -scheme SampleName -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone X” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
