language: swift
osx_image: xcode11.4
#xcode_project: #replace MyNewProject.xcodeproj
#xcode_workspace: #replace MyNewProject.xcworkspace
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

branches:
  only: 
    - master

git:
  depth: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
